//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonVi
    {
        public DonVi()
        {
            this.LichSuCongTacs = new HashSet<LichSuCongTac>();
            this.NhanViens = new HashSet<NhanVien>();
        }
    
        public int id { get; set; }
        public string MaDonVi { get; set; }
        public string TenDonVi { get; set; }
        public string MaLoai { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public System.DateTime NamThanhLap { get; set; }
        public string ChucNang { get; set; }
        public string NhiemVu { get; set; }
    
        public virtual LoaiDonVi LoaiDonVi { get; set; }
        public virtual ICollection<LichSuCongTac> LichSuCongTacs { get; set; }
        public virtual ICollection<NhanVien> NhanViens { get; set; }
    }
}
