//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonVi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonVi()
        {
            this.LichSuCongTac = new HashSet<LichSuCongTac>();
            this.NhanVien = new HashSet<NhanVien>();
        }
    
        public int MaDonVi { get; set; }
        public string TenDonVi { get; set; }
        public int MaLoai { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public System.DateTime NamThanhLap { get; set; }
        public string ChucNang { get; set; }
        public string NhiemVu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuCongTac> LichSuCongTac { get; set; }
        public virtual LoaiDonVi LoaiDonVi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVien> NhanVien { get; set; }
    }
}
