//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class HeSoLuongPhuCap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HeSoLuongPhuCap()
        {
            this.LichSuChuyenBac = new HashSet<LichSuChuyenBac>();
        }
    
        public int MaHeSo { get; set; }
        public string TenHeSo { get; set; }
        public double HeSo { get; set; }
        public string MaNgach { get; set; }
    
        public virtual NgachLuong NgachLuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuChuyenBac> LichSuChuyenBac { get; set; }
    }
}
