//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuCongTac
    {
        public int MaCongTac { get; set; }
        public int MaNV { get; set; }
        public int MaDonVi { get; set; }
        public int MaChucVu { get; set; }
        public string MaNgach { get; set; }
        public System.DateTime NgayLam { get; set; }
        public Nullable<System.DateTime> NgayChuyen { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual DonVi DonVi { get; set; }
        public virtual NgachLuong NgachLuong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
