//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuCongTac
    {
        public int id { get; set; }
        public string MaCongTac { get; set; }
        public string MaNV { get; set; }
        public string MaDonVi { get; set; }
        public string MaChucVu { get; set; }
        public string MaNgach { get; set; }
        public string TenDonVi { get; set; }
        public string TenChucVu { get; set; }
        public string TenNgach { get; set; }
        public System.DateTime NgayLam { get; set; }
        public Nullable<System.DateTime> NgayChuyen { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual DonVi DonVi { get; set; }
        public virtual NgachLuong NgachLuong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
