//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiDonVi
    {
        public LoaiDonVi()
        {
            this.DonVis = new HashSet<DonVi>();
        }
    
        public int id { get; set; }
        public string MaLoai { get; set; }
        public string TenLoai { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<DonVi> DonVis { get; set; }
    }
}
