//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuongThucTe
    {
        public int MaLuong { get; set; }
        public int MaNV { get; set; }
        public System.DateTime NgayLap { get; set; }
        public double HeSoLuong { get; set; }
        public decimal LuongCoBan { get; set; }
        public Nullable<decimal> LuongThucTe1 { get; set; }
        public string TrangThai { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
