//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NgachLuong
    {
        public NgachLuong()
        {
            this.HeSoLuongPhuCaps = new HashSet<HeSoLuongPhuCap>();
            this.LichSuCongTacs = new HashSet<LichSuCongTac>();
        }
    
        public int id { get; set; }
        public string MaNgach { get; set; }
        public string TenNgach { get; set; }
        public double NienHan { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<HeSoLuongPhuCap> HeSoLuongPhuCaps { get; set; }
        public virtual ICollection<LichSuCongTac> LichSuCongTacs { get; set; }
    }
}
