//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.LichSuCongTac = new HashSet<LichSuCongTac>();
            this.LichSuChuyenBac = new HashSet<LichSuChuyenBac>();
            this.LuongThucTe = new HashSet<LuongThucTe>();
        }
    
        public int id { get; set; }
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string MaDonVi { get; set; }
        public string MaChucVu { get; set; }
        public string MaNgach { get; set; }
        public string MaHeSo { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public string DanToc { get; set; }
        public string GioiTinh { get; set; }
        public string CMND { get; set; }
        public string DiaChi { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayNghi { get; set; }
        public Nullable<System.DateTime> NgayHuu { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual DonVi DonVi { get; set; }
        public virtual HeSoLuongPhuCap HeSoLuongPhuCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuCongTac> LichSuCongTac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichSuChuyenBac> LichSuChuyenBac { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuongThucTe> LuongThucTe { get; set; }
        public virtual NgachLuong NgachLuong { get; set; }
    }
}
