//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyLuongEntities : DbContext
    {
        public QuanLyLuongEntities()
            : base("name=QuanLyLuongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChucVu> ChucVu { get; set; }
        public virtual DbSet<DonVi> DonVi { get; set; }
        public virtual DbSet<HeSoLuongPhuCap> HeSoLuongPhuCap { get; set; }
        public virtual DbSet<LichSuCongTac> LichSuCongTac { get; set; }
        public virtual DbSet<LichSuChuyenBac> LichSuChuyenBac { get; set; }
        public virtual DbSet<LoaiDonVi> LoaiDonVi { get; set; }
        public virtual DbSet<LuongThucTe> LuongThucTe { get; set; }
        public virtual DbSet<NgachLuong> NgachLuong { get; set; }
        public virtual DbSet<NhanVien> NhanVien { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
