//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyLuongEntities : DbContext
    {
        public QuanLyLuongEntities()
            : base("name=QuanLyLuongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChucVu> ChucVus { get; set; }
        public virtual DbSet<DonVi> DonVis { get; set; }
        public virtual DbSet<HeSoLuongPhuCap> HeSoLuongPhuCaps { get; set; }
        public virtual DbSet<LichSuChuyenBac> LichSuChuyenBacs { get; set; }
        public virtual DbSet<LichSuCongTac> LichSuCongTacs { get; set; }
        public virtual DbSet<LoaiDonVi> LoaiDonVis { get; set; }
        public virtual DbSet<LuongThucTe> LuongThucTes { get; set; }
        public virtual DbSet<NgachLuong> NgachLuongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
